# Generated by Django 4.2.1 on 2023-05-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Каталог товаров',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Our_site.catalog', verbose_name='Каталог категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=155, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=300, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес продукта')),
                ('expiration_date', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Срок годности')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Our_site.category', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
    ]
